[package]
name = "wa-integrate"
version = "0.1.0"
edition = "2024"
include = ["/src/lib-rs"]

[lib]
path = "/src/lib-rs"
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.100"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.4"
