[workspace]
authors = ["Marvin van Aalst <marvin.vanaalst@gmail.com>"]
channels = ["conda-forge"]
name = "mxlweb"
platforms = [
    "emscripten-wasm32",
    "linux-64",
]
version = "0.1.0"

[feature.wasm]
channels = ["https://repo.mamba.pm/emscripten-forge"]
dependencies = { python = "*", scipy = ">=1.11.1,<2", numpy = ">=2.2.4,<3" }
platforms = ["emscripten-wasm32"]

[feature.host]
channels = ["conda-forge"]
dependencies = { python = "*", scipy = ">=1.11.1,<2", numpy = ">=2.2.4,<3" }
platforms = ["linux-64"]

# make sure that we have the WASM environment installed before building the app
[feature.host.tasks]
build-dist = { cmd = "jupyter lite build --output-dir dist --XeusAddon.prefix=.pixi/envs/wasm" }
setup-wasm = { cmd = "pixi install -e wasm", inputs = ["pixi.lock"] }

# build the jupyterlite app
[feature.host.tasks.build]
cmd = "jupyter lite build --XeusAddon.prefix=.pixi/envs/wasm"
depends-on = ["setup-wasm"]
inputs = ["pixi.lock", "files/"]
outputs = ["_output"]

# serve the jupyterlite app with a "simple server"
[feature.host.tasks.start]
cmd = "python -m http.server 8000 -d _output"
depends-on = ["build"]

[environments]
default = ["host"]
wasm = ["wasm"]
