<script lang="ts">
  import { backends, type Analyses } from "$lib";
  import AnalysesDashboard from "$lib/AnalysesDashboard.svelte";
  import { SectionMain as Main } from "@computational-biology-aachen/design";
  import { initModel } from "./model";
  let analyses: Analyses = $state([
    {
      type: "simulation" as const,
      id: 0,
      idx: 0,
      title: "Simulation",
      col: 1,
      span: 6,
      tEnd: 100,
      xMin: undefined,
      xMax: undefined,
      yMin: undefined,
      yMax: undefined,
      timeoutInSeconds: 20,
      backend: backends.wasmRadau5,
      nTimePoints: 100,
      lineDisplay: "last",
    },
  ]);
</script>

<svelte:head>
  <title>Yokota 1985 - mxlweb</title>
</svelte:head>

<Main pad="tight">
  <AnalysesDashboard
    name={"Yokota 1985"}
    initModel={initModel}
    bind:analyses={analyses}
    equationsOpen={false}
  >
    <h1>Yokota 1985 photorespiration model</h1>
    <p>
      The Yokota 1985 model is a kinetic description of the photorespiratory C2
      cycle in plant chloroplasts and peroxisomes. Glycolate generated by
      Rubisco oxygenase flows through glyoxylate, glycine, serine and
      hydroxypyruvate, while the hydrogen peroxide produced by glycolate oxidase
      is scavenged by catalase.
    </p>
    <p>
      Every enzymatic step follows Michaelis–Menten kinetics, so the model
      traces how carbon and reducing equivalents move through the
      photorespiratory pathway under varying conditions.
    </p>
  </AnalysesDashboard>
</Main>
